#!/bin/bash
set -u

NAME="LS-30"
CONTAINER="rpavlyuk/c7-ls30"
EXISTS="yes"
RUNNING="yes"

# Determing if exists and running
echo "Checking container $NAME status..."
RUNNING=$(docker inspect --format="{{ .State.Running }}" $NAME 2> /dev/null)

set -e

if [ $? -eq 1 ]; then
  echo "$NAME does not exist."
  EXISTS="no"
fi

if [ "$RUNNING" == "false" ]; then
  echo "$NAME is not running."
  RUNNING="no"
fi

# stop existing one
if [ "$RUNNING" == "yes" ];
then
  docker stop $NAME || :
fi
# kill it
if [ "$EXISTS" == "yes" ];
then
  docker rm $NAME || :
fi

# run a new container
docker run  \
  -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
  -p 3000:3000 \
  -p 1681:1681 \
  --name $NAME \
  $CONTAINER
