#!/bin/bash

LS30_HOME="/usr/share/LS30"
SERVICE_CONFIG="/etc/sysconfig/ls-30"

if [ -f "$SERVICE_CONFIG" ];
then
        echo "Reading configuration from $SERVICE_CONFIG"
        . $SERVICE_CONFIG
fi

if [ -z "$LS30_REMOTE_SERVER" ];
then
	echo "WARNING: Undefined ENV variable \"LS30_REMOTE_SERVER\""
	LS30_REMOTE_SERVER=127.0.0.1:1681
fi

$LS30_HOME/bin/alarm-daemon.pl -h $LS30_REMOTE_SERVER 127.0.0.1:1681
