container: docker.io/rpavlyuk/c7-ls30
created: 2017-10-11 16:53:53.501852
name: LS-30
ports:
        3000/tcp: 3000
        1681/tcp: 1681
        8888/tcp: 8888
        2222/tcp: 2222
        2812/tcp: 2812
volumes:
        /usr/share/LS30/clam:
                bind: /usr/share/LS30/clam
                mode: rw
privileged: false
tty: false
working_dir: /root
command:
        host:
                post: docker exec LS-30 /usr/bin/ls-30-set-remote 192.168.1.220:1681 && docker exec LS-30 /usr/bin/ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa  -q -N "" && docker cp /root/.ssh/authorized_keys LS-30:/root/.ssh/
environment:
        LS30_SERVER: '127.0.0.1:1681'
network_mode: bridge
